GET http://161.35.239.203/boca

###

@phpsessid = m6epdpc2bc0jgjucc21pft4sgr
@biscoitobocabombonera = 1707837464-09b322c1d9720d8e6b7e98e18b946e8c268747281525cf60f9aad18b148c64df

###

# NOTE: password URL parameter = js_myhash(js_myhash(password)+PHPSESSID);
GET http://161.35.239.203/boca/index.php?name=team1&password=8e5ff00f19599f49cd3f35e1eaa27fe31c1fdb94da2699be2949fd7399c96f70
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

GET http://161.35.239.203/boca/team/run.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

GET http://161.35.239.203/boca/team/problem.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

# https://stackoverflow.com/a/20321259
# boundary is a user-defined string used to separate the parts of a multipart request
# in the request body, the boundary should always be preceded by two hyphens
# and the last boundary should also be followed by two hyphens;
# you can submit a form in the browser with the Dev Tools open and then look at the
# Network tab to see the POST request that was sent in both parsed and source format
# in Chrome, a boundary looks like this: ----WebKitFormBoundarymKMwtSgaUDMWOUVw
# which means, and used in request body, it should be: ------WebKitFormBoundarymKMwtSgaUDMWOUVw
#
POST http://161.35.239.203/boca/team/run.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}
Content-Type: multipart/form-data; boundary=XXX

--XXX
Content-Disposition: form-data; name="confirmation"

confirm
--XXX
Content-Disposition: form-data; name="problem"

1
--XXX
Content-Disposition: form-data; name="language"

1
--XXX
Content-Disposition: form-data; name="sourcefile"; filename="A.c"
Content-Type: text/x-csrc

< ./A.c
--XXX
Content-Disposition: form-data; name="Submit"

Send
--XXX--
