GET http://161.35.239.203/boca

###

@phpsessid = h6qfs9do9qlt546vtiuiumh03a
@biscoitobocabombonera = 1707842275-b1928f09f3ebd3a017c26cbb0344923525c6e0cdeae57a3f1a6b7f61ca3f4a45

###

# NOTE: password URL parameter = js_myhash(js_myhash(password)+PHPSESSID);
GET http://161.35.239.203/boca/index.php?name=team1&password=d6b15ff81b44917b3c6b190958da7385bfd077c5f98c99618f1920b21f16425f
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

GET http://161.35.239.203/boca/team/run.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

GET http://161.35.239.203/boca/team/problem.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}

###

# https://stackoverflow.com/a/20321259
# boundary is a user-defined string used to separate the parts of a multipart request
# in the request body, the boundary should always be preceded by two hyphens
# and the last boundary should also be followed by two hyphens;
# you can submit a form in the browser with the Dev Tools open and then look at the
# Network tab to see the POST request that was sent in both parsed and source format
# in Chrome, a boundary looks like this: ----WebKitFormBoundarymKMwtSgaUDMWOUVw
# which means, and used in request body, it should be: ------WebKitFormBoundarymKMwtSgaUDMWOUVw
#
POST http://161.35.239.203/boca/team/run.php
Cookie: biscoitobocabombonera={{biscoitobocabombonera}}; PHPSESSID={{phpsessid}}
Content-Type: multipart/form-data; boundary=XXX

--XXX
Content-Disposition: form-data; name="confirmation"

confirm
--XXX
Content-Disposition: form-data; name="problem"

1
--XXX
Content-Disposition: form-data; name="language"

1
--XXX
Content-Disposition: form-data; name="sourcefile"; filename="A.c"
Content-Type: text/x-csrc

< ./A.c
--XXX
Content-Disposition: form-data; name="Submit"

Send
--XXX--
